//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.ProjectToUsers = new HashSet<ProjectToUser>();
        }
    
        public int p_ID { get; set; }
        public string pName { get; set; }
        public string pDesc { get; set; }
        public int pPM_ID { get; set; }
        public int pCust_ID { get; set; }
        //0= New Request, 1= WIP, 2= Completed
        public int pStatus { get; set; }
        //NULL= No request, 1= Accept, 2= Reject, 3= Drop
        public Nullable<int> pRequest { get; set; }
        public string Pm { get; set; }
        public string Cust { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectToUser> ProjectToUsers { get; set; }
    }
}
