//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectToUser
    {
        public int r_ID { get; set; }
        public int p_ID { get; set; }
        public int u_ID { get; set; }
        public Nullable<int> response { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual User User { get; set; }
    }
}
